### ISSUE TITLE
failed to install the package from pip

### ISSUE THREAD

**Issue by HazhoHuman** [PropelAuth/propelauth-flask#2]
```
Collecting propelauth-flask
  Using cached propelauth-flask-2.0.0.tar.gz (4.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      /env_af/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
```

**Comment by andrew-propelauth** [comment]
Thanks for writing in! We aren't able to reproduce this on our end - testing with python 3.9 and a few versions of pip. 

Could you try bypassing the cache:
```
pip install --no-cache-dir propelauth_flask
```

and could you send us the full output? Feel free to send to support@propelauth.com if you'd prefer.

**Comment by HazhoHuman** [comment]
yes I followed the documentations page with hyphen not underscore, see the screenshot:
![image](https://user-images.githubusercontent.com/116259088/220759067-4f84e433-5dde-4dc9-8fa0-bf7de87ced63.png)

**Comment by HazhoHuman** [comment]
still the error is same:
![image](https://user-images.githubusercontent.com/116259088/220759463-bc4e576d-0a05-4d42-bb7b-5e90e8a7a07f.png)

**Comment by andrew-propelauth** [comment]
Got it - we believe we've identified the issue and just released v2.0.2 to address it. Could you see if that version fixes the issue?

**Comment by HazhoHuman** [comment]
I think now the error raised from -py package not this one, not sure though
```
/var/www/devs/af/server# pip install --no-cache-dir propelauth_flask
Collecting propelauth_flask
  Downloading propelauth-flask-2.0.2.tar.gz (4.7 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: flask>=0.9 in /var/www/devs/env_af/lib/python3.9/site-packages (from propelauth_flask) (2.2.2)
Collecting propelauth-py
  Downloading propelauth-py-3.0.1.tar.gz (9.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      /var/www/devs/env_af/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
        warnings.warn(
      WARNING: The wheel package is not available.
      WARNING: The repository located at mirrors.cloud.aliyuncs.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.cloud.aliyuncs.com'.
      ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
      ERROR: No matching distribution found for pytest-runner
      Traceback (most recent call last):
        File "/var/www/devs/env_af/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/var/www/devs/env_af/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp8elqwfi3', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'pytest-runner']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4tpun7xo/propelauth-py_6d2d9505b1ca46c4a79a77c11625a4d7/setup.py", line 7, in <module>
          setup(
        File "/var/www/devs/env_af/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/var/www/devs/env_af/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/var/www/devs/env_af/lib/python3.9/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/var/www/devs/env_af/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "/var/www/devs/env_af/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "/var/www/devs/env_af/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
          return installer(requirement)
        File "/var/www/devs/env_af/lib/python3.9/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/var/www/devs/env_af/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/var/www/devs/env_af/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp8elqwfi3', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'pytest-runner']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by andrew-propelauth** [comment]
Got it, ok that makes sense, we'll need to make the same change there. Sorry about that, we'll roll that out now and ping this shortly.

**Comment by andrew-propelauth** [comment]
Ok, second time's the charm :)
Version 2.0.3 includes a new version of propelauth-py which also fixes the issue there.

Let us know if that resolves it!

**Comment by HazhoHuman** [comment]
Done, with a warning:
```
Installing collected packages: propelauth-py, propelauth_flask
  DEPRECATION: propelauth-py is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for propelauth-py ... done
  DEPRECATION: propelauth_flask is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for propelauth_flask ... done
```
